### ISSUE TITLE
Abort adding task

### ISSUE THREAD

**Issue by JonasJurczok** [JonasJurczok/factorio-todo-list#10]
If you are adding a task and actually realize you don't want to you should be able to abort adding it.

**Comment by georgehank** [comment]
Came here to report that.  :grinning:

**Comment by JonasJurczok** [comment]
:D yes.. luckily an easy fix. Expect a new release later today.

Am 21.09.2017 17:45 schrieb "Jürgen A. Erhard" <notifications@github.com>:

Came here to report that. 😀

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JonasJurczok/factorio-todo-list/issues/10#issuecomment-331197851>,
or mute the thread
