### ISSUE TITLE
Bad Timestamp on Chinese Locale file

### ISSUE THREAD

**Issue by Rybadour** [JonasJurczok/factorio-todo-list#100]
Hey,

I help write a program that parses mods for Factorio. A user recently reported a problem with your Mod that caused our program to crash. The file "/locale/zh-CN/default.cfg" seems to have a weird timestamp which is causing the issue. I installed the mod today using the in-game mod UI.

It's not a big deal as our program mostly needs recipe information but this could break other users or programs as well and it seems like a quick fix.

Thanks!

**Comment by JonasJurczok** [comment]
What do you mean with timestamp? In the metadata? Which one is it? Modified
or created?

**Comment by Rybadour** [comment]
The modified timestamp was something like 0001-01-01 00:00:00

**Comment by JonasJurczok** [comment]
Hey,
sorry for only coming back to this now.

While the timestamp is technically valid it is of course wrong. I dug into it and can only assume that the travis server I'm using to build this mod had a hickup.

Can you please check the .17 version and see if everything is fine for you there? On my windows machine it looks okay (but yeah, windows...). I can only check on a mac tomorrow.

**Comment by JonasJurczok** [comment]
I assume it is okay for now. If you still have issues please reopen the ticket.
Thanks :)

**Comment by Rybadour** [comment]
Not sure why I didn't notice it before but it looks like quest.cfg in that same directory has the same issue.

**Comment by JonasJurczok** [comment]
I believe all the files have that problem.

I build the mod with continuous delivery in GitHub actions. I assume the
docker image does not get primed with the correct time.

I'll investigate that.

**Comment by Rybadour** [comment]
Thanks!
