### ISSUE TITLE
Crash when opening sub tasks

### ISSUE THREAD

**Issue by emilyselwood** [JonasJurczok/factorio-todo-list#146]
**Describe the bug**
Expanding a todo list entry with a reasonable number of tasks crashes

Factorio version: 0.18.9 build 49691 win64

**To Reproduce**
1. Open todo list
2. Click on Details for a task that has sub tasks (a task without subtasks opens ok)
3. See error at end of bug report.

**Expected behavior**
Expected task list to show sub tasks.

**Screenshots**
![Factorio 0 18 9 26_02_2020 21_47_56](https://user-images.githubusercontent.com/645622/75391313-bec9bf00-58e1-11ea-8154-b9b6a0082145.png)
![Factorio 0 18 9 26_02_2020 21_48_05](https://user-images.githubusercontent.com/645622/75391316-c0938280-58e1-11ea-89e9-9e0b3a6a30f5.png)

Error message shown below:

The mod Todo List (18.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Todo-List::on_gui_click (ID 1)
Unknown sprite "utility/remove"
stack traceback:
	__Todo-List__/todo/ui/main_frame.lua:429: in function 'add_row_to_main_table'
	__Todo-List__/todo/ui/main_frame.lua:399: in function 'add_subtask_to_main_table'
	__Todo-List__/todo/ui/main_frame.lua:312: in function 'add_subtasks_to_task_table'
	__Todo-List__/todo/ui/main_frame.lua:295: in function 'add_task_to_table'
	__Todo-List__/todo/features/main_ui.lua:71: in function 'refresh_task_table'
	__Todo-List__/todo/features/details_view.lua:10: in function 'on_show_task_details_click'
	__Todo-List__/todo/todo.lua:145: in function 'on_gui_click'
	__Todo-List__/control.lua:20: in function <__Todo-List__/control.lua:19>
stack traceback:
	[C]: in function 'add'
	__Todo-List__/todo/ui/main_frame.lua:429: in function 'add_row_to_main_table'
	__Todo-List__/todo/ui/main_frame.lua:399: in function 'add_subtask_to_main_table'
	__Todo-List__/todo/ui/main_frame.lua:312: in function 'add_subtasks_to_task_table'
	__Todo-List__/todo/ui/main_frame.lua:295: in function 'add_task_to_table'
	__Todo-List__/todo/features/main_ui.lua:71: in function 'refresh_task_table'
	__Todo-List__/todo/features/details_view.lua:10: in function 'on_show_task_details_click'
	__Todo-List__/todo/todo.lua:145: in function 'on_gui_click'
	__Todo-List__/control.lua:20: in function <__Todo-List__/control.lua:19>

**Comment by emilyselwood** [comment]
I've attached the save file at the point this happens
[_autosave1.zip](https://github.com/JonasJurczok/factorio-todo-list/files/4258361/_autosave1.zip)

The following mods are in use:
* LogisticTrainNetwork 1.12.1
* OpteraLib 0.2.0
* Power Armor Mk3 0.2.13
* Squeak Through 1.8.0
* Todo-List 18.0.0
* Waterfill_v17 0.18.0
* base 0.18.9

**Comment by JonasJurczok** [comment]
Hey,
thanks for the detailed report.

The root cause is that apparently some icons from the base game got renamed.

The fix should be easy (have proper local icons). Unfortunately I'm
currently moving flats and won't have a working computer until Friday
(hopefully).

Until then you can either stop using sub tasks or remove the icon from the
configuration.

Both workarounds are not really durable, sorry :/

**Comment by emilyselwood** [comment]
Fair enough. At least it is not something I've done to break it. Good luck with the move.

**Comment by Dilise** [comment]
Hi, I corrected the error of the missing sprite. Issued a pull request. New sprite-utility/trash_bin.
![изображение](https://user-images.githubusercontent.com/16350731/76147168-59cd5080-60bb-11ea-85a2-88fba7fb1d40.png)

**Comment by Dilise** [comment]
I found another flat picture of the trash:
![изображение](https://user-images.githubusercontent.com/16350731/76147310-d3197300-60bc-11ea-8bd5-fd914c4b9f9f.png)
The name of the sprite:
![изображение](https://user-images.githubusercontent.com/16350731/76147330-08be5c00-60bd-11ea-9ee5-8aff2f6315cf.png)

**Comment by JonasJurczok** [comment]
A new version has been released. Thank you very much for the help and patience.

I'm leaving this open for a couple days to check if it is actually fixed :)

**Comment by emilyselwood** [comment]
Seems fixed on mine. Thanks @JonasJurczok and @Dilise

**Comment by JonasJurczok** [comment]
Awesome :)
