### ISSUE TITLE
Super crazy request from a non coder

### ISSUE THREAD

**Issue by argash** [JonasJurczok/factorio-todo-list#151]
I love your mod and use it all the time when playing Factorio, especially with friends. I'm wondering though, would it be possible to port it to Space Engineers? We recently started playing it and while we really enjoy it, no one has written a similar mod for it. I would be more than happy to donate a copy of the game or make some other similar donation!

Also I totally understand if this is not something y'all are interested in so please feel free to tell me to piss off!

**Comment by JonasJurczok** [comment]
hahah thanks :)

Unfortunately I barely have time to play Factorio and starting another game is not an option for me at the moment.
If you want to start a project there I happily give advice and explain design decisions, though :)

Thanks again for the request and good luck with your Spaceships!

Best,
Jonas
