### ISSUE TITLE
Focus task title field on 'new task' event

### ISSUE THREAD

**Issue by hoylemd** [JonasJurczok/factorio-todo-list#177]
I've been using this for awhile, and one thing that annoys me is when I click the 'add task' button, I have to click the title field before I can start typing the new task.

I believe such a method on ui elements does exist: https://forums.factorio.com/viewtopic.php?t=38511

**Comment by hoylemd** [comment]
just FYI, I'm planning to make a pull request for this.  Should be like a one line change :p

**Comment by hoylemd** [comment]
https://lua-api.factorio.com/latest/LuaGuiElement.html#LuaGuiElement.focus API reference

**Comment by JonasJurczok** [comment]
Awesome, looking forward to it :)
