### ISSUE TITLE
[Idea][project]Link a task to a map tag

### ISSUE THREAD

**Issue by hoylemd** [JonasJurczok/factorio-todo-list#181]
I often want to associate a task with a location (e.g. build a wall at a choke point), and indeed map tags are a good alternative to an explicit todo list. - its what I used before I discovered this mod, actually!

This is obviously a large undertaking, but I think I can break it down to a few steps:

- determine a way to link a task to a map tag under-the-hood (e.g. I imagine map tags have some kind of global id -  YARM works with them a bit, that might be a good place to research)
- Add an option to automatically make a todo list task when a map tag is manually created.
- (not sure if possible) Add a 'link map tag' button to the task edit/create popup to allow the user to link a tag after the task has been created
- Automatically delete the map tag once the linked task is completed (it probably won't be possible to restore a map tag if the task is un-completed - I'm fine with that)

I'm planning to work on this myself, so code review and approval is probably the only support that's needed, and I'll make that as easy as I can :)

**Comment by JonasJurczok** [comment]
There is already #34 which kinda has the same goal.

I thought about adding a optional map UI component to the subtask detail screen that you can point to things you want.
But of course a map tag would be way cooler :)

**Comment by hoylemd** [comment]
cool. I'll copy this stuff to that issue and close this one. No need for a dupe :)

**Comment by hoylemd** [comment]
dupe of #34
