### ISSUE TITLE
the mod detected, but the button didn't show up

### ISSUE THREAD

**Issue by ShinoIro** [JonasJurczok/factorio-todo-list#187]
running on Factorio 1.1.30 GOG version
currently installed mod :
1. Nanobots
2. stdlib
3. Todo-list
Nanobots mod works fine, but this mod doesn't
device : ASUS X454Y

**Comment by JonasJurczok** [comment]
Good morning,

can you please check the mod settings? There is an option to hide the button completely. 

And can you check the shortcut buttons near the toolbar. Is a „add task“ shortcut available?

**Comment by ShinoIro** [comment]
> 
> Good morning, can you please check the mod settings? There is an option to hide the button completely. And can you check the shortcut buttons near the toolbar. Is a „add task“ shortcut available?

unfortunately under the Setting -> Mod Setting, i only have the nanobots mod only.
about the second question though, i don't get it.. i've checked everything under setting, but found nothing..

**Comment by JonasJurczok** [comment]
Hmm that is strange.
If you don't see settings for TODO list it suggests the mod has not been installed correctly.

There are a couple settings available on the "per player" page of the mod settings.

Can you please verify that the mod has been installed and is loaded?

**Comment by Alexander-Serov** [comment]
I believe this issue is not pertinent anymore or has been resolved by the subsequent updates. I will close, but please comment if you think it's still valid.
