### ISSUE TITLE
2.0 Update?

### ISSUE THREAD

**Issue by Skyl3lazer** [JonasJurczok/factorio-todo-list#198]
Hello!

Do you plan on updating it to at least be compatible with Space Age / 2.0?

Thanks!

**Comment by Kyoj1n** [comment]
The README says they stopped development and are looking for someone to take over.

**Comment by Skyl3lazer** [comment]
I see that, but if there's very little in the way of breaking changes they may still come back just to get a minimum viable product working again :)

**Comment by mike1172** [comment]
You can try this "continuation" of the mod I created here:

https://mods.factorio.com/mod/Todo-List-Continued

I will not be developing a new version, only trying to make a 2.0 compatible version but provided "as-is".

Should the original author return to this mod, I can mark the "continuation" as deprecated.

**Comment by JonasJurczok** [comment]
Hey,

I'm honestly surprised and honoured by this request :) I didn't expect that this issue would get 4 votes.

Unfortunately I have stopped playing factorio (work, life, family, kids...) and thus also have not followed the changes made to the modding API.

If there are only minor changes and/or one of you is willing to provide a PR I'm happy to release a new version.

Also as said in the readme, I'm also happy about people taking over the repository. The pipeline still works and everything is prepared for someone with more time for this :)

**Comment by mike1172** [comment]
> Hey,
> 
> I'm honestly surprised and honoured by this request :) I didn't expect that this issue would get 4 votes.
> 
> Unfortunately I have stopped playing factorio (work, life, family, kids...) and thus also have not followed the changes made to the modding API.
> 
> If there are only minor changes and/or one of you is willing to provide a PR I'm happy to release a new version.
> 
> Also as said in the readme, I'm also happy about people taking over the repository. The pipeline still works and everything is prepared for someone with more time for this :)

I can open a PR for some of the know changes, such as sprite name changes and some class type changes in the API. 

Currently though, there seems to be some inconsistent behavior with the global table being initialized on dedicated servers. Not sure how minor of a change that will be to resolve as the issue does not seem to happen for single player clients. I'll see if i can pinpoint it over the next few days.

**Comment by mike1172** [comment]
Apparently Factorio changed the Global table name to "Storage" in 2.0 which would explain the inconsistent behavior since Global would now act as a normal script level variable and not a Global serialized and persistent variable.  

https://lua-api.factorio.com/latest/auxiliary/storage.html

I'll be playing around with an updated version replacing Global with Storage (plus the other sprite/class changes) and see if it becomes stable. Hopefully this is the last surprise...

**Comment by Alexander-Serov** [comment]
Hey! Thanks all for reporting. The 2.0 update will be [merged](https://github.com/JonasJurczok/factorio-todo-list/pull/201) and released this week. Sorry for the delay.

**Comment by Alexander-Serov** [comment]
Fixed. Please update to v19.8.0 and create a new issue if there any bugs!
