### ISSUE TITLE
Attempt to index a `nil` value

### ISSUE THREAD

**Issue by LegendaryLinux** [JonasJurczok/factorio-todo-list#199]
The mod experienced an error, and caused the game to immediately end and return to the main menu.

Here is the save file which produced the issue:
[space_age.zip](https://github.com/user-attachments/files/17528440/space_age.zip)

The mod provided the following dump text:
```
Error while running event Todo-List-Continued::on_gui_click (ID 1)
__Todo-List-Continued__/todo/features/export_task.lua:6: attempt to index global 'global' (a nil value)
stack traceback:
	__Todo-List-Continued__/todo/features/export_task.lua:6: in function 'update_export_dialog_button_state'
	__Todo-List-Continued__/todo/ui/main_frame.lua:57: in function 'create_maximized_frame'
	__Todo-List-Continued__/todo/features/main_ui.lua:69: in function 'maximize_main_frame'
	__Todo-List-Continued__/todo/features/main_ui.lua:58: in function 'on_maximize_button_click'
	__Todo-List-Continued__/todo/todo.lua:94: in function 'on_gui_click'
	__Todo-List-Continued__/control.lua:20: in function <__Todo-List-Continued__/control.lua:19>
```

Here is my rather short mod list, so you don't need to scratch your head while trying to load the save file.
![image](https://github.com/user-attachments/assets/7db34e00-d7ea-40a3-9d85-8132131c73dd)

**Comment by JustDen1234** [comment]
same here

**Comment by LegendaryLinux** [comment]
There is further discussion of this issue on the [Factorio Forums](https://mods.factorio.com/mod/Todo-List-Continued/discussion/6718e0647562cb79838ad867). The mod author is aware of the issue and is working on a fix.

**Comment by Alexander-Serov** [comment]
Should be solved by [this PR](https://github.com/JonasJurczok/factorio-todo-list/pull/201) and hopefully released this week.

**Comment by Alexander-Serov** [comment]
Fixed. Pleas upgrade to v19.8.0
