### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Shtriger** [JonasJurczok/factorio-todo-list#200]
Die Mod ✔ Todo List - Continued (20.0.2) hat einen Fehler verursacht, der nicht behoben werden kann.
Bitte informiere den Autor der Mod über diesen Fehler.

Error while running event Todo-List-Continued::on_gui_click (ID 1)
__Todo-List-Continued__/todo/features/export_task.lua:6: attempt to index global 'global' (a nil value)
stack traceback:
	__Todo-List-Continued__/todo/features/export_task.lua:6: in function 'update_export_dialog_button_state'
	__Todo-List-Continued__/todo/ui/main_frame.lua:57: in function 'create_maximized_frame'
	__Todo-List-Continued__/todo/features/main_ui.lua:69: in function 'maximize_main_frame'
	__Todo-List-Continued__/todo/features/main_ui.lua:58: in function 'on_maximize_button_click'
	__Todo-List-Continued__/todo/todo.lua:94: in function 'on_gui_click'
	__Todo-List-Continued__/control.lua:20: in function <__Todo-List-Continued__/control.lua:19>

**Comment by Alexander-Serov** [comment]
Hey @Shtriger , @DaPutzy ,

Thanks for reporting. Will be solved in the next release after https://github.com/JonasJurczok/factorio-todo-list/pull/201 is merged.
