### ISSUE TITLE
TODO List Not Loading in 2.0

### ISSUE THREAD

**Issue by otobot1** [JonasJurczok/factorio-todo-list#204]
Factorio Version: 2.0.21
TODO List Version: 19.6.0
Thanks for working to update this mod for Space Age! Unfortunately, the new update doesn't seem to have worked. With all other mods disabled (including the official Space Age ones), TODO List doesn't show up on my screen, in my toolbar, or in my mod settings.
![no todo](https://github.com/user-attachments/assets/ad9a467f-cbb0-415f-9de7-28daafc7b755)

**Comment by Alexander-Serov** [comment]
Hey! Yes, something has changed since factorio 2.0.0. We are looking into it. If you have ideas, don't hesitate to open a PR!
