### ISSUE TITLE
Export/import tasks (as with blueprint strings)

### ISSUE THREAD

**Issue by Tarrke** [JonasJurczok/factorio-todo-list#29]
I think we should be able to import a preset list of tasks. 

If I'm beggining a new game I always start the same, and I  still forgot to correctly size the first furnace for iron or oversize the copper smelting area. So I'd like to have a nice preset list of what to do and what size I want them to be.

**Comment by JonasJurczok** [comment]
Okay. I like the idea but how would you implement this?
Given the limited file access that factorio itself grants this might be hard...

**Comment by JonasJurczok** [comment]
You could do something like "put a .csv file in a specified location"...

or do you want presets? like initial sets of tasks that you can select?

**Comment by Tarrke** [comment]
I think we should go for presets at the moment. My original idea was to make something like the blueprint strings, so you can make you list in a game, export it and reimport it in an other game. But my lua skills are too poor to even find where to start working with base64 encoded json.

**Comment by JonasJurczok** [comment]
Ahh okay.

I like that idea. And it should actually be fairly simple to implement.
I like it :D

**Comment by Tarrke** [comment]
I'm looking forward for your implementation of this!

**Comment by JonasJurczok** [comment]
There are multiple ways of encoding/decoding to base64.
None of them are native to lua.

There are some that only require a minimal amount of code to be include.
Some other methods require libraries (which is harder to do in our context).

Some solutions can be found here: http://lua-users.org/wiki/BaseSixtyFour

**Comment by JonasJurczok** [comment]
Exporting should be done from the main screen.
Open a dialog with a list of all the tasks and checkboxes besides them.
Export selected tasks to a single string (task sets)

**Comment by Tarrke** [comment]
Seems right.
