### ISSUE TITLE
'Send to top' / 'Send to bottom' function

### ISSUE THREAD

**Issue by hoylemd** [JonasJurczok/factorio-todo-list#40]
I'm often finding that I'm adding tasks to my to-do list that are very low or very high priority, so it'd be nice to be able to send tasks to the top or bottom of the list at will.

A checkbox on the creation dialog would also work, just for creating the item at the top instead of the bottom.

(Also, Is there any way to resize the text? It's a little too big, so the list takes up a lot of my screen.)

**Comment by JonasJurczok** [comment]
Hi,
thats a really good idea. I'm not sure if adding more buttons solves the problem or if we just add it to the task creation screen..

What do you think?

Regarding text resizing: I haven't checked that at all so far, but will give it a look. See #41

**Comment by hoylemd** [comment]
I agree that more buttons on the to-do list widget wouldn't be a great solution.  I sort of meant it more abstractly... 'function' is a better word.

An option on the creation dialog would cover 90% of my use cases though.

I wonder if it would be possible to implement a 'drag to sort' feature? That would be SUPER useful, but I don't know if that's even possible in Factorio.

I don't have the ui in front of me, but if I remember, the sorting buttons say 'Up' and 'Down'.  If we changed those to just have a small arrow or chevron icon, then they'd both be the same size and smaller than they are now.  That might free up space to do a sort of double-chevron, or chevron-to-line icon to indicate moving to the end of the list in the given direction.

MVP implementation would probably just be an option on the task creation dialog though.  That would cover 90% of my use cases.  I'm imagining a radio button something like:

Add to:
- [x] Top
- [ ] Bottom

**Comment by JonasJurczok** [comment]
Okay, that is true. I couldn't get the icons to work last time but can give
it another try.

Regarding drag and drop: that was our first idea. Unfortunately factorio UI
events don't allow that :/

Michael D. Hoyle <notifications@github.com> schrieb am Do., 26. Juli 2018,
18:46:

**Comment by hoylemd** [comment]
I checked a little later and the sorting buttons already are arrows, but they're fairly narrow.  If we also compress the UI a bit in #41, That might make top and bottom buttons fit :)

**Comment by JonasJurczok** [comment]
Looking forward to it :)

Michael D. Hoyle <notifications@github.com> schrieb am Do., 26. Juli 2018,
22:53:
