### ISSUE TITLE
When minimized the UI should display the first task 

### ISSUE THREAD

**Issue by Tarrke** [JonasJurczok/factorio-todo-list#48]
Using the todo list today I had to save and quit then load my game quite a lot of times. Sitting back at the computer I can't remember what to do then add to open the UI to check the first task. Maybe add a way to  get a view on the first task assigned to me.

What do you think?

**Comment by Tarrke** [comment]
Duplicates #47

**Comment by hoylemd** [comment]
I'd say less 'duplicate' and more 'we had the same idea at the same time' 😆
