### ISSUE TITLE
Add Russian translation

### ISSUE THREAD

**Issue by TheMrEvgen** [JonasJurczok/factorio-todo-list#52]
Hello, please add Russian translation

`[todo]
todo_list=Задачи
title_done=Готово
title_task=Задача
title_assignee=Куратор
title_edit=Редактировать

minimize=Выход
add=Добавить
add_title=Добавить новую задачу
add_task=Задача
add_assignee=Куратор
persist=Сохранить
cancel=Отменить
update=Обновить

unassigned=Неназначенный
assign_self=Взять
show_done=Показывать завершенные задачи
hide_done=Скрыть завершенные задачи

todo_maximize_button_caption=__1__: __2__
nothing_todo=Нет задач.

[controls]
todolist-toggle-ui=Закрыть/Открыть Задачи

[mod-setting-name]
todolist-show-button=Показать"Задачи" кнопку.
todolist-show-log=Показать сообщения журнала отладки в окне чата.
todolist-window-height=Окно списока задач высота
todolist-auto-assign=Автоматическое назначение задач

[mod-setting-description]
todolist-show-button=Если включен всегда появится кнопка "Задачи" в левом верхнем углу.\nЕсли отключить "Задачи" можно добраться только горячими клавишами (Shift-T по умолчанию).
todolist-show-log=Если включена, то мод будет выводить отладочные сообщения в окно чата.\nВнимание: есть много из них :)
todolist-window-height=Высота окна списока задач. По умолчанию-600.
todolist-auto-assign=Если есть только один игрок в игре, автоматически назначать задачи для игрока.`

**Comment by JonasJurczok** [comment]
Thank you very much :)
I'll add it in the next version.

**Comment by JonasJurczok** [comment]
Sorry for the delay.

I added your translations in #55 . 
If you want can you please provide the missing translations?
Thanks!

**Comment by TheMrEvgen** [comment]
`add_top=Добавить в начало`

**Comment by TheMrEvgen** [comment]
`add_top=Добавить в начало

todolist-click-edit-task=Редактирование задачи кнопкой мыши

todolist-click-edit-task=Если включено, средней кнопкой мыши откроет всплывающее окно редактирования. По умолчанию щелкните правой кнопкой мыши.

[string-mod-setting]
todolist-click-edit-task-right-button=Правая кнопка
todolist-click-edit-task-middle-button=Средняя кнопка`

**Comment by JonasJurczok** [comment]
Awesome, thanks :)
