### ISSUE TITLE
Show green Tick when current task is completed

### ISSUE THREAD

**Issue by JonasJurczok** [JonasJurczok/factorio-todo-list#59]
To better indicate that you should pick something new add a green tick to the minimized button if the task is completed.

**Comment by Tarrke** [comment]
Where this tick should be displayed ?

**Comment by JonasJurczok** [comment]
Yeah but after the last changes this actually makes no sense anymore.

Because if there is a task then it is shown. If there is no assigned task (all are completed) then there is an indication for how many tasks are still available...

I'll close this. It's impractical at the moment.
