### ISSUE TITLE
Show created/modified by

### ISSUE THREAD

**Issue by JonasJurczok** [JonasJurczok/factorio-todo-list#60]
It would be nice to see who created/last modified an issue.

**Comment by Tarrke** [comment]
This hsould not be too difficult to get on.

**Comment by Tarrke** [comment]
To be done:
1. add a field to store this information
2. add a label to display the information
3. add the localiation for the new texts

**Comment by JonasJurczok** [comment]
0. add tests :D

**Comment by Tarrke** [comment]
Ho I need to check how to do theses then...

**Comment by JonasJurczok** [comment]
All good. Github had issues today. Apparently they fixed it and even managed to replay all modifications :)
