### ISSUE TITLE
remove custom json encoding

### ISSUE THREAD

**Issue by JonasJurczok** [JonasJurczok/factorio-todo-list#64]
https://forums.factorio.com/viewtopic.php?t=59906

With 0.17 there will be native json encode/decode in Factorio.
We can remove our own json encoder/decoder then

**Comment by Tarrke** [comment]
Humm not quite sure where the json encoder/decoder is... is that the serpent thing?

**Comment by Tarrke** [comment]
Any how, we should add the 0.17 tag to this one.

**Comment by JonasJurczok** [comment]
I'm currently working on the import/export functionality with base64 encoded strings (like for blueprints).
For this you need a json encoder to transform tables from/to strings. In the forum link above they state that from 0.17. they'll actually expose the internal one to all mods :)

**Comment by Tarrke** [comment]
See #29 and #69
