### ISSUE TITLE
Verify showing first line works for empty first lines

### ISSUE THREAD

**Issue by JonasJurczok** [JonasJurczok/factorio-todo-list#67]
The button shows the first line of an assigned task.
Currently it is unclear how the button behaves if the task starts with an empty line.

Add a test to cover this edge case.

Expected behaviour: The first non empty line should be shown

**Comment by JonasJurczok** [comment]
"[^\r\n]*" might be the solution

**Comment by Tarrke** [comment]
I did some test it's working as intended.

**Comment by Tarrke** [comment]
This one can be closed.
