### ISSUE TITLE
Optional quest mode

### ISSUE THREAD

**Issue by JonasJurczok** [JonasJurczok/factorio-todo-list#74]
It should be possible to switch the mod to a quest log and calling tasks quests.

**Comment by Tarrke** [comment]
Do you see this as an option or a key stroke switch?

**Comment by JonasJurczok** [comment]
I would say an option.
I think the idea is fun but has limited use cases :)

**Comment by Tarrke** [comment]
Should the quests be repeatable? Should we stock the quests resolver instead of task assignee?

**Comment by Omnifarious** [comment]
I like this idea as well. I made some changes to the language file for English to change button labels around and things. I could clone this repo and submit my changes as a pull request, though I think that way of doing things is a bad idea for this change. But it might be a useful jumping off point for discussion.

**Comment by Tarrke** [comment]
Can't realy speak in Jonas' place but I think he would prefer a clean PR for every feature.

**Comment by JonasJurczok** [comment]
Sorry, totally forgot to reply here.

I appreciate the pull request but I would definitely put this behind an
option. Otherwise everyone has to go full RPG mode :)
