### ISSUE TITLE
Option for auto deleting?

### ISSUE THREAD

**Issue by JonasJurczok** [JonasJurczok/factorio-todo-list#82]
**Auto delete tasks**
Currently completed tasks build up in a huge list.
Usually you never look at them again.

**Describe the solution you'd like**
We could add an option to automatically delete tasks instead of marking them as complete.
Then the completed list would not be that long.

**Additional context**
Or a modifier? shift + complete click deletes?

**Comment by Tarrke** [comment]
It should be an option.

My idea is to build a list of tasks while doing a game. Then, at the end, I should have a nice ToDo List for an other game, I just undo all tasks, export them, and load them in my new game. Adding a shortcut without multiple anoying popups may result in loss of tasks.

**Comment by JonasJurczok** [comment]
Exporting does not require undoing them :)

But would you do this every time or just in the first game?
I personally just start from scratch all the time but that's just me.

What about click marks it complete, shift click deletes. But you have to set a mod option to allow deletion.
Then you have to do something to enable it and then still change your behaviour?

**Comment by Tarrke** [comment]
> What about click marks it complete, shift click deletes. But you have to set a mod option to allow deletion.
> Then you have to do something to enable it and then still change your behaviour?

That could work.
