### ISSUE TITLE
Todo List Mailbox

### ISSUE THREAD

**Issue by JonasJurczok** [JonasJurczok/factorio-todo-list#84]
Crazy idea: 
If you are somewhere outside and think about your factory there is no way to put that into your todo list.

How about a mail address (personalized) where you can send random mails to. When you log into the game next time they are fetched from the mailbox and added to your todo list.

I have no idea if this is techically possible.. and if someone would actually use it :D

Alternative: have a small mobile app that creates todo list export strings. Then you can create the task on the fly, mail it to yourself and then import it manually.

**Comment by Tarrke** [comment]
The second options seems more do-able. The first is crazy as we should have access to the Internet and mailboxes inside Factorio. We can't have access to the full lua os lib and specially the time management part of it.

I like the idea, certainly won't use it though.

**Comment by JonasJurczok** [comment]
It's technically interesting. But nothing more :D

You could get luasocket into the mod and try to get it to work. Then you would have to write all the HTTP interaction yourself but technically it should be possible then.

Anyhow.. not needed most probably and insanely complicated.

**Comment by Tarrke** [comment]
> You could get luasocket into the mod and try to get it to work. Then you would have to write all the HTTP interaction yourself but technically it should be possible then.

Oh, we may be able to send mail then. Sending s easier than reading mails.
