### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by kingmax007** [JonasJurczok/factorio-todo-list#95]
Can I put a complete German translation of aour mod into my mod to publishing it?

You don't have to worry about the German translation, because my mod has it then.

Please feel free to write me. Thank you.

**Comment by JonasJurczok** [comment]
Hi,
the mod already has a german translation shipped with it.
If you think it's incomplete or you want to change it please tell me, then we can talk about it.

Also there is #74 still open for adopting different wordings if this s what you are up to :)

Please tell me more :)

**Comment by kingmax007** [comment]
```

todolist-auto-assign=**Wenn nur ein Spieler online ist, übergebe die Aufgabe diesem Spieler.** _If there is only one player in the game, auto-assign the task to this player._
todolist-click-edit-task=**Wenn es aktiviert wurde, kannst du mit "Mittlerer Maustaste (Scrollradklick)" draufklicken und dann editieren. Standartmäßig ist es auf "Rechte Maustaste".** _If enabled the middle click will open the edit popup. Default on right click._

[string-mod-setting]
todolist-click-edit-task-right-button=**Rechte Maustaste**
todolist-click-edit-task-middle-button=**Mittlere Maustaste(Scrollrad)**

```

_abc_ - english
**abc** - german

Have a nice day.... :)

**Comment by JonasJurczok** [comment]
Did I honestly forgot to translate that? m(
That is embarassing, especially being from Germany myself.

Thanks for pointing it out. I'll fix this asap...

**Comment by kingmax007** [comment]
Gut, dann können wir jetzt in deutsch weiter reden :D

**Comment by JonasJurczok** [comment]
:D Du kannst auch gerne nen pull request aufmachen wenn du willst. Dann geht es noch etwas schneller :)

**Comment by kingmax007** [comment]
Einen Pullrequest? :D Was soll das sein? Ich hab mir nur Github zugelegt, damit ich unter anderem dir schreiben konnt ^_^' :D

**Comment by JonasJurczok** [comment]
Ah okay. Danke für die Mühe :)
Im Prinzip kannst du damit direkt Änderungen vorschlagen. Das einfachste ist wenn du hier im Repository zu der Datei navigierst die du ändern willst und dort auf den Stift klickst. Dann kannst du sie im Browser verändern und bekommst ganz unten dann die Option nen Pull Request aufzumachen. 

Dann kann ich direkt auf akzeptieren klicken und es ist direkt im Code, ohne das wir lange hin und her machen müssen. Ansonsten mache ich das später selber, wie du magst :)

**Comment by kingmax007** [comment]
Alles klar... moment :)
